### ISSUE TITLE
Where cost-sensitive loss is computed?

### ISSUE THREAD

**Issue by ghost** [594422814/UDT_pytorch#5]
Hi. I read your paper and got very interested in your unsupervised tracking.

My question is that where in the codes cost-sensitive loss (A^i_{motion}) is implemented.
I found `train_UDT.py` includes reduction of samples with very high loss values (A^i_{drop}), but I cannot find where it weights samples according to the motion.
Is it not implemented yet?

**Comment by 594422814** [comment]
Sorry, I did not implement this. 
The results reported in the paper are obtained using the Matlab code. The I wrote this pytorch version.  Since the A_i_drop is necessary (otherwise we observe that our unsupervised loss cannot well converge). But I forgot to implement the cost-sensitive loss. I will add this later.

**Comment by ghost** [comment]
I see. Thank you!

**Comment by swrdZWJ** [comment]
I meet the same problem and when do you release the lastest and complete version with implementation of cost-sensitive loss？Thanks～～

**Comment by ReedZyd** [comment]
When do you realse the latest and completed version with implementation of cost-sensitive loss?
