### ISSUE TITLE
About dataset.

### ISSUE THREAD

**Issue by ReedZyd** [594422814/UDT_pytorch#7]
Is the dataset you used unprocessed after downloading from the official website? The dataset I downloaded from the official website seems to be unable to use because of the label name and the image size. Can you share a complete dataset file? Thank you very much.

**Comment by ReedZyd** [comment]
The dataset I downloaded from the official website seems to be unable to use because of the label name and the image size. Can you share a complete dataset file? I will be very grateful.

**Comment by 594422814** [comment]
We use the standard VID dataset (video object detection dataset instead of the image detection dataset) without further processing. The only difference is we rename the "train_0000""train_0001"... folders as "a""b""c"...
Please check train/dataset/parse.py for more details. You can also refer to DCFNet for the detailed training dataset information.
