### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by swrdZWJ** [594422814/UDT_pytorch#8]
Hi，Thanks for your excellent work，but I meet some difference from the original paper.Do you have a plan for a newer version and when do you release the complete version？Thanks ：）

**Comment by 594422814** [comment]
Hi, the results in our paper are obtained using the matconvnet version. Please refer to it for more details.
Compared with the matconvnet version, the only difference is that this code omits the weighted loss, which only has a slight performance influence. 
Since I obtained similar results using this prototype, I did not further improve this code later. Sorry.
